### PR TITLE
Add Java e2e tests

### PR DESCRIPTION
**Pull request by jasonjkeller**
Resolves https://github.com/newrelic/newrelic-java-agent/issues/1860
Resolves https://github.com/newrelic/newrelic-java-agent/issues/1861

### CODE REVIEW

**Comment by jasonjkeller** [comment]
hmmm looks like the test is failing on waiting for the test app pod to be ready. Not sure if the test app is failing to start (it started fine with local testing) or if it's just taking too long to start.

```
kubectl wait --for=condition=Ready -n default --all pods
error: timed out waiting for the condition on pods/test-app-java-688b644576-b7mb2
```

I'm going to try a longer sleep. 

Eventually I want to swap in a lighter weight test app.

**Comment by jasonjkeller** [comment]
Actually, the problem is that the "Build init container for e2e test" step isn't setting an agent version:

```
#4 [2/3] ADD https://download.newrelic.com/newrelic/java-agent/newrelic-agent//newrelic-agent-.jar /newrelic-agent.jar
#4 ERROR: invalid response status 404
```

**Comment by tippmar-nr** [comment]
> Actually, the problem is that the "Build init container for e2e test" step isn't setting an agent version:
> 
> ```
> #4 [2/3] ADD https://download.newrelic.com/newrelic/java-agent/newrelic-agent//newrelic-agent-.jar /newrelic-agent.jar
> #4 ERROR: invalid response status 404
> ```

@jasonjkeller Is there an "unversioned" latest release of the Java agent that you can reference here? We had to do a little bit of dancing on the .NET side to add an unversioned tarball to our release process to accommodate this particular use case. There really won't be a way for the tests to be supplied with a version number - so I think Java will either need an unversioned jar file or some other way to get "latest version".

**Comment by jasonjkeller** [comment]
@tippmar-nr Thanks. I ended up moving the agent download logic into a little shell script invoked by the init container Dockerfile that will download the agent version matching the build arg if it's provided, otherwise it will just default to the current version. That seems to have done the trick.

**Review by TimPansino — APPROVED** [review]

**Pull request merged**
